import type { Metadata } from "next";
import { Inter } from "next/font/google";


import "./globals.css";


import Navbar from "@/components/Navbar";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Candidate Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
      <Script src="/tinymce/tinymce.min.js" />
        <Navbar />
        {children}</body>
    </html>
  );
}
